### REGISTER Request
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "alex@email.com",
  "password": "azerty",
  "fullName": "Alex Black"
}

### LOGIN Request
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "alex@email.com",
  "password": "azerty"
}

### TOKEN Request
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGV4QGVtYWlsLmNvbSIsImlhdCI6MTczMjEzOTYxMCwiZXhwIjoxNzMyMTQ2ODEwfQ.-bXYC20DfoHtCMxlHOVM7_9sLqGUh5Wu-otJr6lf-7M

{
}

### TOKEN Request USERES
GET http://localhost:8080/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGV4QGVtYWlsLmNvbSIsImlhdCI6MTczMDkwNDExNywiZXhwIjoxNzMwOTA3NzE3fQ.xELRj0xul_z8SkVzAaV50PoI2QB58qjv72dHHY2Jpq0

{
}

