### REGISTER Request
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "alex@email.com",
  "password": "azerty",
  "fullName": "Alex Black"
}

### LOGIN Request
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "alex@email.com",
  "password": "azerty"
}

### TOKEN Request
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGV4QGVtYWlsLmNvbSIsImlhdCI6MTc0OTY0NDc0MSwiZXhwIjoxNzQ5NjUxOTQxfQ.Vo8ZqEHPVmQPVFsyTWRoO1aH5UgDF2qCwk2wAX1Gdcc

{
}

### TOKEN Request USERES
GET http://localhost:8080/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGV4QGVtYWlsLmNvbSIsImlhdCI6MTc0OTY0MzQ5MSwiZXhwIjoxNzQ5NjUwNjkxfQ.ycqfmdfnFOszS-42BdTGrvbIxebHjZBVWv0kqK0A7gE

{
}

